ALTER TABLE `players`
MODIFY COLUMN `player_class`  enum('WARRIOR','GLADIATOR','TEMPLAR','SCOUT','ASSASSIN','RANGER','MAGE','SORCERER','SPIRIT_MASTER','PRIEST','CLERIC','CHANTER','ENGINEER','GUNNER','ARTIST','RIDER','BARD','PAINTER') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `race`;

