/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 04:04:44 PM EET 
//

package com.aionemu.packetsamurai.utils.collector.data.npcMoves;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for NpcMove complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NpcMove">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="z" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="mask" type="{http://www.w3.org/2001/XMLSchema}byte" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NpcMove")
public class NpcMove {
	@XmlAttribute(name = "speed")
	protected Float speed;

	@XmlAttribute(name = "mask")
	protected Byte mask;

	@XmlAttribute(name = "z", required = true)
	protected float z;

	@XmlAttribute(name = "y", required = true)
	protected float y;
	
	@XmlAttribute(name = "x", required = true)
	protected float x;
	
	@XmlTransient
	protected long time;

	public NpcMove() {
	}

	public NpcMove(float x, float y, float z, byte mask, long time) {
		this.x = x;
		this.y = y;
		this.z = z;
		this.mask = mask;
		this.time = time;
	}

	/**
	 * Gets the value of the x property.
	 */
	public float getX() {
		return x;
	}

	/**
	 * Sets the value of the x property.
	 */
	public void setX(float value) {
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 */
	public float getY() {
		return y;
	}

	/**
	 * Sets the value of the y property.
	 */
	public void setY(float value) {
		this.y = value;
	}

	/**
	 * Gets the value of the z property.
	 */
	public float getZ() {
		return z;
	}

	/**
	 * Sets the value of the z property.
	 */
	public void setZ(float value) {
		this.z = value;
	}

	/**
	 * Gets the value of the mask property.
	 * 
	 * @return possible object is {@link Byte }
	 */
	public byte getMask() {
		if (mask == null) {
			return ((byte) 0);
		}
		else {
			return mask;
		}
	}

	/**
	 * Sets the value of the speed property.
	 */
	public void setMask(Byte value) {
		this.mask = value;
	}
	
	public Float getSpeed() {
		if (speed == null) {
			return ((float) 0);
		}
		else {
			return speed;
		}
	}

	/**
	 * Sets the value of the speed property.
	 */
	public void setSpeed(float value) {
		if (value == 0)
			this.speed = null;
		else
			this.speed = value;
	}
	
	public long getTime() {
		return time;
	}

}
