/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 04:04:44 PM EET 
//


package com.aionemu.packetsamurai.utils.collector.data.npcMoves;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aionemu.packetsamurai.utils.collector.data.npcMoves package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NpcMoves_QNAME = new QName("", "npcMoves");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aionemu.packetsamurai.utils.collector.data.npcMoves
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NpcMoveList }
     * 
     */
    public NpcMoveList createNpcMoveList() {
        return new NpcMoveList();
    }

    /**
     * Create an instance of {@link NpcMove }
     * 
     */
    public NpcMove createNpcMove() {
        return new NpcMove();
    }

    /**
     * Create an instance of {@link Npc }
     * 
     */
    public Npc createNpc() {
        return new Npc();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NpcMoveList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "npcMoves")
    public JAXBElement<NpcMoveList> createNpcMoves(NpcMoveList value) {
        return new JAXBElement<NpcMoveList>(_NpcMoves_QNAME, NpcMoveList.class, null, value);
    }

}
