/**
 * This file is part of Aion-Lightning <aion-lightning.org>.
 *
 *  Aion-Lightning is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Aion-Lightning is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details. *
 *  You should have received a copy of the GNU General Public License
 *  along with Aion-Lightning.
 *  If not, see <http://www.gnu.org/licenses/>.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.06 at 03:44:15 DU CEST 
//

package com.aionemu.packetsamurai.utils.collector.data.npcData;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NpcStat")
public class NpcStat implements Comparable<NpcStat> {

	@XmlAttribute
	protected int npcId;
	@XmlAttribute
	protected int lvl;
	@XmlAttribute
	protected int xp;
	@XmlAttribute
	protected int hp;
	@XmlAttribute
	protected int titleId;
	@XmlAttribute
	private int npcType;

	/**
	 * Gets the value of the npcId property.
	 * 
	 * @return possible object is {@link Integer }
	 */
	public int getNpcId() {
		return npcId;
	}

	/**
	 * Sets the value of the npcId property.
	 * 
	 * @param value
	 *          allowed object is {@link Integer }
	 */
	public void setNpcId(int value) {
		this.npcId = value;
	}

	/**
	 * Gets the value of the lvl property.
	 * 
	 * @return possible object is {@link Integer }
	 */
	public int getLvl() {
		return lvl;
	}

	/**
	 * Sets the value of the lvl property.
	 * 
	 * @param value
	 *          allowed object is {@link Integer }
	 */
	public void setLvl(int value) {
		this.lvl = value;
	}

	/**
	 * Gets the value of the xp property.
	 * 
	 * @return possible object is {@link Integer }
	 */
	public int getXp() {
		return xp;
	}

	/**
	 * Sets the value of the xp property.
	 * 
	 * @param value
	 *          allowed object is {@link Integer }
	 */
	public void setXp(int value) {
		this.xp = value;
	}

	/**
	 * Gets the value of the hp property.
	 * 
	 * @return possible object is {@link Integer }
	 */
	public int getHp() {
		return hp;
	}

	/**
	 * Sets the value of the hp property.
	 * 
	 * @param value
	 *          allowed object is {@link Integer }
	 */
	public void setHp(int value) {
		this.hp = value;
	}

	/**
	 * Gets the value of the titleId property.
	 * 
	 * @return possible object is {@link Integer }
	 */
	public int getTitleId() {
		return titleId;
	}

	/**
	 * Sets the value of the titleId property.
	 * 
	 * @param value
	 *          allowed object is {@link Integer }
	 */
	public void setTitleId(int value) {
		this.titleId = value;
	}

	public int getNpcType() {
		return npcType;
	}

	public void setNpcType(int npcType) {
		this.npcType = npcType;
	}

	@Override
	public int compareTo(NpcStat o) {
		return npcId - o.npcId;
	}

	@Override
	public String toString() {
		return "NpcStat [npcId=" + npcId + ", lvl=" + lvl + ", hp=" + hp + ", titleId=" + titleId + ", npcType=" + npcType + "]";
	}

}
